---
title: "Mid-points of `glm()` frequentist models"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{midpoints-glm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r setup}
library(midpoints)
library(ggplot2)
library(ggdist)

vocabulary <- sim_data()
head(vocabulary)
```


# Generalized Linear Model (`glm`)

## One categorical predictor

```{r glm-1}
fit <- glm(y ~ x,
           family = binomial("logit"),
           data = vocabulary)

summary(fit)
```

```{r glm-1-midpoint}
midpoints <- midpoint.glm(fit, vocabulary)

head(midpoints)
```

```{r fig-glm-1}
model.preds <- fitted(object = fit)

vocabulary |> 
    ggplot(aes(x, y)) +
    geom_hline(yintercept = 1/2,
               linetype = "dotted") +
    geom_jitter(height = 1/20,
                shape = 1,
                stroke = 1,
                alpha = 1/2) +
    geom_line(aes(y = model.preds),
              linewidth = 3/4) + 
    geom_segment(data = midpoints,
                 aes(x = .mid, xend = .mid,
                     y = 0, yend = 1/2),
                 colour = "red") +
    geom_point(data = midpoints,
               aes(x = .mid, y = 1/2),
               colour = "red") 
```

## Two predictors (one categorical)

```{r glm-2-data}
vocabulary_2 <- purrr::map2_dfr(
    .x = c(15, 25),
    .y = c("a", "b"),
    .f =  \(x, y) {
        d <- sim_data(n_id = 5, x0 = x)
        d$pred_1 <- y
        return(d)
    })

head(vocabulary_2)
```


```{r glm-2}
fit_2 <- glm(y ~ x + pred_1,
             family = binomial("logit"),
             data = vocabulary_2)

summary(fit_2)
```

```{r glm-2-midpoint}
midpoints <- midpoint.glm(fit_2, vocabulary_2)

head(midpoints)
```

```{r fig-glm-2}
model.preds <- fitted(object = fit_2)

vocabulary_2 |> 
    ggplot(aes(x, y, colour = pred_1)) +
    geom_hline(yintercept = 1/2,
               linetype = "dotted") +
    geom_jitter(height = 1/20,
                shape = 1,
                stroke = 1,
                alpha = 1/2) +
    geom_line(aes(y = model.preds),
              linewidth = 3/4) + 
    geom_segment(data = midpoints,
                 aes(x = .mid, xend = .mid,
                     y = 0, yend = 1/2)) +
    geom_point(data = midpoints,
               aes(x = .mid, y = 1/2)) 
```

## Two predictors (both continuous)

```{r glm-3-data}
vocabulary_3 <- purrr::map2_dfr(
    .x = c(15, 25),
    .y = c(0, 4),
    .f =  \(x, y) {
        d <- sim_data(n_id = 5, x0 = x)
        d$pred_1 <- rnorm(nrow(d), y, 1)
        return(d)
    })

head(vocabulary_3)
```


```{r glm-3}
fit_3 <- glm(y ~ x + pred_1,
             family = binomial("logit"),
             data = vocabulary_3)

summary(fit_3)
```

```{r glm-3-midpoint}
nd <- data.frame(pred_1 = c(-1, 0, 1))
midpoints <- midpoint.glm(fit_3, nd)
midpoints$pred_1 <- as.factor(nd$pred_1)

head(midpoints)
```

```{r fig-glm-3}
model.preds <- expand.grid(pred_1 = nd$pred_1, 
                           x = vocabulary$x)

model.preds$y <- plogis(predict(object = fit_3, 
                                model.preds))
model.preds$pred_1 <- as.factor(model.preds$pred_1)

vocabulary_3 |> 
    ggplot(aes(x, y)) +
    geom_hline(yintercept = 1/2,
               linetype = "dotted") +
    geom_jitter(height = 1/20,
                shape = 1,
                stroke = 1,
                alpha = 1/2) +
    geom_line(data = model.preds,
              aes(colour = pred_1),
              linewidth = 3/4) +
    geom_segment(data = midpoints,
                 aes(x = .mid, xend = .mid,
                     y = 0, yend = 1/2,
                     colour = pred_1)) +
    geom_point(data = midpoints,
               aes(x = .mid, y = 1/2,
                   colour = pred_1)) 
```

## Two predictors (one categorical) and interaction

```{r glm-4-data}
vocabulary_4 <- vocabulary_2

head(vocabulary_4)
```


```{r glm-4}
fit_4 <- glm(y ~ x * pred_1,
             family = binomial("logit"),
             data = vocabulary_4)

summary(fit_4)
```

```{r glm-4-midpoint}
midpoints <- midpoint.glm(fit_4, vocabulary_4)

head(midpoints)
```

```{r fig-glm-5}
model.preds <- fitted(object = fit_5)

vocabulary_5 |> 
    ggplot(aes(x, y, colour = pred_1)) +
    geom_hline(yintercept = 1/2,
               linetype = "dotted") +
    geom_jitter(height = 1/20,
                shape = 1,
                stroke = 1,
                alpha = 1/2) +
    geom_line(aes(y = model.preds),
              linewidth = 3/4) + 
    geom_segment(data = midpoints,
                 aes(x = .mid, xend = .mid,
                     y = 0, yend = 1/2)) +
    geom_point(data = midpoints,
               aes(x = .mid, y = 1/2)) 
```


## Two predictors (both continuous) and interaction

```{r glm-5-data}
vocabulary_5 <- vocabulary_3

head(vocabulary_5)
```


```{r glm-5}
fit_5 <- glm(y ~ x * pred_1,
             family = binomial("logit"),
             data = vocabulary_5)

summary(fit_4)
```

```{r glm-5-midpoint}
nd <- data.frame(pred_1 = c(-1, 0, 1))
midpoints <- midpoint.glm(fit_5, nd)
midpoints$pred_1 <- as.factor(nd$pred_1)

head(midpoints)
```


```{r fig-glm-5}
model.preds <- expand.grid(pred_1 = nd$pred_1, 
                           x = vocabulary_5$x)

model.preds$y <- plogis(predict(object = fit_5, 
                                model.preds))
model.preds$pred_1 <- as.factor(model.preds$pred_1)

vocabulary_5 |> 
    ggplot(aes(x, y)) +
    geom_hline(yintercept = 1/2,
               linetype = "dotted") +
    geom_jitter(height = 1/20,
                shape = 1,
                stroke = 1,
                alpha = 1/2) +
    geom_line(data = model.preds,
              aes(colour = pred_1),
              linewidth = 3/4) +
    geom_segment(data = midpoints,
                 aes(x = .mid, xend = .mid,
                     y = 0, yend = 1/2,
                     colour = as.factor(pred_1))) +
    geom_point(data = midpoints,
               aes(x = .mid, y = 1/2,
                   colour = as.factor(pred_1))) 
```
